### ISSUE TITLE
Lancer Dofus 1.09.1

### ISSUE THREAD

**Issue by volgar1x** [Emudofus/Dofus#1]
Salut, grâce à Defura on peut rejouer à Dofus 1.09.1 ! problème : fichier de lang introuvable. Le fichier de configuration fait référence à dl.dofus.com, lien mort depuis le temps ... Vous avez une idée pour corriger ça ?

**Comment by nightwolf93** [comment]
Cette version est tres lointaine. Ca m'interesserai de voir si elle est
supporter par les emulateurs actuels ou si le protocol a enormement changer.

**Comment by volgar1x** [comment]
elle date de 2005 :) justement j'aurais bien aimé faire un petit truc pour le fun mais impossible de lancer le jeu

**Comment by vendethiel** [comment]
t'as essayé d'utiliser les langs actuelles ?

**Comment by volgar1x** [comment]
non, ça ne marche pas non plus
