### ISSUE TITLE
Compiling back instruction,

### ISSUE THREAD

**Issue by yelhouti** [Emudofus/Dofus#16]
I would like to do some modification on the client then recompile it, but I can't event manage to recompile it back using falshDevelop, any help please.
Thanks

**Comment by yelhouti** [comment]
Blackrush, some help please ? :)

**Comment by volgar1x** [comment]
I'm no Adobe Air pro, you gotta do it all by yourself. Good luck :wink:

**Comment by yelhouti** [comment]
Never coded with actionScript, but I see it very similar to Java, so I'll manage to change it as I want, but compilation, I really didn't manage, I'll wait for an answer.
Thanks for label anyway  :)

**Comment by Sadikk** [comment]
Decompile the client with FFDec, do your changes with the Edit tab and then  save the result.

**Comment by yelhouti** [comment]
Thank you sadik I've sent you an e-mail from here: http://rootsheep.info/contact/
