### ISSUE TITLE
goto _label_ not working

### ISSUE THREAD

**Issue by yelhouti** [Emudofus/Dofus#17]
## when I try to recompile a project, I get the following error:

C:\Users\Userf\ASWorkspace\Dofus\com\ankamagames\dofus\logic\shield\SecureModeManager.as(471): col: 31 Error: Syntax error: expecting rightbrace before semicolon.
                goto _label_10;
                              ^
C:\Users\User\ASWorkspace\Dofus\com\ankamagames\dofus\logic\shield\SecureModeManager.as(479): col: 26 Error: Syntax error: expected a definition keyword (such as function) after attribute goto, not _label_9.
            goto _label_9;
                         ^
## Build halted with errors (fcsh).

It seems that the compiler doesn't recognize the instruction goto, any help of how you overcome that?

**Comment by volgar1x** [comment]
Try your chance on Stackoverflow.
