### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by iR3SH** [Emudofus/Dofus#19]
I want to use [Sourcegraph](https://sourcegraph.com) for Dofus code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/Emudofus/Dofus. (It should only take 30 seconds.)

Thank you!

**Comment by vendethiel** [comment]
ActionScript is not supported. Sourcegraph's advanced code search, browsing, and usage examples are only available for supported languages. If the language was detected incorrectly, or to use only basic repository operations, you can proceed anyway.
