### ISSUE TITLE
Vraies sources d'1.29.1?

### ISSUE THREAD

**Issue by Crystals** [Emudofus/Dofus#3]
Quelqu'un a déjà réussi a avoir les sources d'1.29.1 sous formes de classes AS2 au lieu de la structure actuelle, ou les a converties ?
Je suis en train de convertir, c'est légèrement long, mais j'me demandais au cas ou.

**Comment by vendethiel** [comment]
Fais un outil pour ça, pas à la main Oo

**Comment by Crystals** [comment]
J'suis encore plus paresseux de faire ça ;D
Mais en fait c'est surtout qu'y'aurait des problèmes quand même, il y a souvent plusieurs vars qui sont mentionnées dans le code sans qu'elles soient définies clairement dans la classe. Je les rajoute donc après, soit en suivant les erreurs "xxx is missing" ou en c/c les vars définies dans 1.09.1. 
Il y a aussi les extends qui sont à rajouter et que je trouve souvent grâce aux sources d'1.09.1.

**Comment by volgar1x** [comment]
Quel est l'intérêt de faire ça ? C'est suffisamment lisible pour ce qu'on en fait actuellement IMO

**Comment by Crystals** [comment]
Oui, pour faire un émulateur ça va.
Moi c'est surtout pouvoir le modifier directement sans passer par le core ou flasm et avoir quelque chose d'utilisable/compilable sur FlashDevelop.

**Comment by volgar1x** [comment]
Bonne chance dans ce cas :-D

**Comment by Crystals** [comment]
Merci, en espérant que je ne créé pas une tonne d'erreurs à la fin quand ça va rouler ;p
Pour l'instant impossible de lancer le client tant que toutes les classes ne sont pas converties D:

**Comment by Crystals** [comment]
Et merde :') depuis tout le temps que j'suis dans l'émulation, je n'en avais aucune idée mais j'ai toujours eu les sources du loader 1.25 (build:5182) à la place du 1.29.1 (build:5026)  :')
Aucune idée d'ou j'me suis procuré ça, ça fait des années ^^
L'ai remarqué en voulant faire les challenges de combats sur mon emu... Dofus 1.25 n'avait pas encore ce système :(
